#ifndef SKILL_METADATA_H
#define SKILL_METADATA_H

typedef enum
{
    SKILL_CATEGORY_NONE = 0,

    SKILL_CATEGORY_LANGUAGE,
    SKILL_CATEGORY_FRAMEWORK,
    SKILL_CATEGORY_DATABASE,
    SKILL_CATEGORY_TOOL,
    SKILL_CATEGORY_CONCEPT,
    SKILL_CATEGORY_SOFT_SKILL

} SkillCategory;

typedef enum
{
    SKILL_STATUS_NOT_STARTED = 0,

    SKILL_STATUS_LEARNING,

    SKILL_STATUS_PRACTICING,

    SKILL_STATUS_MASTERED

} SkillStatus;

#endif